config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  get 'user/photo'
  get 'user/comment'
  root to: 'user#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comment
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users_all = User.all
  end
  def photo
    @user_id=params[:user_id]
    @user_firstname=params[:user_firstname]
    @user_lastname=params[:user_lastname]
    @photos = Photo.where("user_id= ?",@user_id )
  end
  def comment
    @photo_id=params[:photo_id]
    @user_firstname=params[:user_firstname]
    @user_lastname=params[:user_lastname]
    @comments = Comment.includes(:user).where(" photo_id= ?",@photo_id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
        head{
            align-items: center;
        }
        h1{
            background-color: antiquewhite;
            flex-direction: column;
            justify-content: center;
            text-align: center;

        }
        h3{
            background-color: lemonchiffon;
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }
        h2{
            background-color: azure;
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }


    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/comment.html.erb
<% if @comments.size > 0 %>
  <h3 style="font-family: 'Bookman Old Style'; color: crimson"><%= @comments.size %> people have commented on <%=  @user_firstname+""+@user_lastname%>'s Photo.</h3>
<div class="message-board">
  <table border="5" bordercolor="pink" align="center">
    <tr>
      <th>Commented_by</th>
      <th>Commented_Time</th>
      <th>Comments</th>
    </tr>

    <% @comments.each do |comment| %>
      <tr>
        <td align="center" valign="center" height=50 width=50><%= link_to comment.user.first_name+""+comment.user.last_name,user_photo_path(:user_id => comment.user_id,:user_firstname => comment.user.first_name,:user_lastname => comment.user.last_name)%></div></td>
        <td align="center" valign="center" height=50 width=50><%= comment.date_time%></div></td>
        <td align="center" valign="center" height=50 width=50><%= comment.comment_text %></div></td>
      </tr>
    <% end %>
  </table>
</div>
<% else %>
  <h1>NO COMMENTS</h1>
<% end %>

app/views/user/index.html.erb
<h1 style="font-family: 'Bookman Old Style'; color: crimson">PhotoSite User List</h1>
<h2 style="font-family: 'Bell MT';">There are <%= @users_all.size %> Users</h2>
<div class="message-board">
  <table border="5" bordercolor="pink" align="center">
    <tr>
      <th>User</th>
      <th>FullName</th>
    </tr>

    <% @users_all.each do |user| %>
      <tr>
        <td align="center" valign="center" height=50 width=50><%= user.id%></td>
        <td align="center" valign="center" height=50 width=50><%= link_to user.first_name+""+user.last_name,user_photo_path(:user_id => user.id,:user_firstname => user.first_name,:user_lastname => user.last_name)%></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/user/photo.html.erb
<% if @photos.size > 0 %>
<h3 style="font-family: 'Bookman Old Style'; color: crimson"><%= @user_firstname+""+ @user_lastname %> Posted <%= @photos.size %> Photos.</h3>
<div class="message-board">
  <table border="5" bordercolor="pink" align="center" cell-spacing=0>
    <tr>
      <th>Photos</th>
      <th>Created_Time</th>
      <th>Comments</th>
    </tr>

    <% @photos.each do |photo| %>
      <tr>
        <td border=3 height=100 width=100> <%= image_tag "https://photosite-rojabalakrishnan.s3.amazonaws.com/#{photo.file_name}",:size => "400x300"%></td>
        <td border=3 height=100 width=100 align="center" valign="center"><%= photo.date_time%></div></td>
        <td border=3 height=100 width=100 align="center" valign="center"><%= link_to "comments",user_comment_path(:photo_id => photo.id,:user_firstname => @user_firstname,:user_lastname => @user_lastname)%></td>
      </tr>
    <% end %>
  </table>
</div>
<% else %>
  <h1>NO PHOTOS</h1>
<% end %>